[package]
name = "nitro-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
raiko-lib = { workspace = true }
raiko-primitives = { workspace = true }

aws-nitro-enclaves-nsm-api = "0.4.0"
serde_bytes = "0.11"
once_cell = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
